---
- name: install postgresql
  yum: name={{ item }} state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2
    - libselinux-python

- name: postgresql initdb
  shell: service postgresql initdb

- name: backup pg_hba.conf
  shell: mv /var/lib/pgsql/data/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf.default

- name: pg_hba.conf setting
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600

- name: start postgresql
  service: name=postgresql state=started  enabled=yes

- name: postgres user sudores
  lineinfile: 
    dest: /etc/sudoers.d/postgres 
    owner: root
    group: root
    mode: 0440
    line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: create user
  user: name={{ dbuser }} password={{ dbpass }}

- name: create postgres user
  postgresql_user: 
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    state: present
    login_user: postgres
    role_attr_flags: CREATEDB,LOGIN
  sudo_user: postgres
  sudo: yes

